### ISSUE TITLE
Security risk

### ISSUE THREAD

**Issue by gau1991** [arush-sal/shellscripts#4]
From readme
```
Php is interfacing with MySQL by root account and no root password is set
```
Non setting a root password a security risk. Either you can set MySQL password or You can ask user to do that

**Comment by arush-sal** [comment]
From the README file "Php is interfacing with MySQL by root account and no root password is set, incase some other account is being used. That has to be edited in line 121 and 122.". But still, if you ask so then I'll pop a message in there.
