### ISSUE TITLE
Setting Up Database Fails

### ISSUE THREAD

**Issue by harshadyeola** [arush-sal/shellscripts#5]
Please check the error below  while setting up database.

```
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)
```

**Comment by arush-sal** [comment]
Could you please provide a more descriptive information regarding the error?

**Comment by harshadyeola** [comment]
@arush-sal 
Your script fails while creating database for the site. The requirement for script is that it should setup wordpress for the given domain with minimum inputs from user.

```
+ db=harshad.com_db
+ cmd='create database harshad.com_db'
+ [[ -e /var/lib/mysql/harshad.com_db ]]
+ mysql -uroot -h localhost -e 'create database harshad.com_db'
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)
+ exitfn
+ ((  1  ))
+ echo
```

**Comment by arush-sal** [comment]
@harshadyeola Added a default password for the root account. The error should not occur now. Please do check and confirm.

**Comment by harshadyeola** [comment]
@arush-sal 
Same issue again. I think the fix applied is incorrect. Adding default password is security concern.
Please do the needful tests before commenting here.
Please test script at your end first. Also please specify in README , how to use your  script.

```  
inflating: /usr/share/nginx/html/wordpress/wp-includes/rest-api.php  [text]  
  inflating: /usr/share/nginx/html/wordpress/wp-includes/update.php  [text]  
  inflating: /usr/share/nginx/html/wordpress/wp-includes/comment.php  [text]  
  inflating: /usr/share/nginx/html/wordpress/wp-config-sample.php  [text]  
+ exitfn
+ ((  0  ))
+ db=example_db_db
+ cmd='create database example_db_db'
+ [[ -e /var/lib/mysql/example_db_db ]]
+ mysql -uroot -h localhost -e 'create database example_db_db'
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)
+ exitfn
+ ((  1  ))
+ echo
```

**Comment by arush-sal** [comment]
@harshadyeola I would need more details of your test environment, as what variant of ubuntu server your are using(e.g: as per my last observation you guys are using vagrant VM instead of baremetal), any special rule or condition configuration that have been configured, etc because on my side the script is running all good in both default baremetal or vagrant variant.

**Comment by harshadyeola** [comment]
@arush-sal 
 we are testing your script on fresh vagrant box with folllowing details :

```
root@vagrant-ubuntu-trusty-64:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.4 LTS
Release:	14.04
Codename:	trusty
```
There is no special configuration. we are using fresh vagrant box with above OS.
 As indicated in previous comment your script is failing while creating database for the site.

If your script requires any other inputs that `domain` then please specify  in your README.

**Comment by arush-sal** [comment]
@harshadyeola Script is fully fixed and functional now. Please do check and confirm. So that the issue can be closed.

**Comment by harshadyeola** [comment]
@arush-sal 
Now I have checked with fresh setup and found following issue. It seems different than previous:

````
  inflating: /usr/share/nginx/html/wordpress/wp-config-sample.php  [text]  
ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.com_db' at line 1

Last command exited with non 0 status. Exiting.
```

**Comment by arush-sal** [comment]
@harshadyeola Well sir, I have updated the README file. MySQL doesn't allow special character such as, “/”, “\”, “.”, or characters that are not allowed in file names to be used as database name. So that's an invalid input case.

**Comment by harshadyeola** [comment]
@arush-sal 
So when you ask for domain name , I entered `harshad.com` Is that invalid input??
If mysql does not allow special chars then you can convert `harshad.com` to `harshad_com`.

**Comment by arush-sal** [comment]
@harshadyeola Now that, is an additional input validation condition to be inplaced. I'll add that if you ask so. But in meanwhile please test the issue without the "."(period) so that I can close this issue, and request you to open a new one for that.

**Comment by harshadyeola** [comment]
@arush-sal 
Well the script worked now with input `harshad` for domain name. I suggest you to modify your script so that the it validates input like `harshad.com`.

Also there is another issue I will be creating.

**Comment by arush-sal** [comment]
@harshadyeola Thank you. Currently working on that only.
